import com.pdfoxide.core.Pdf;
import com.pdfoxide.core.PdfBuilder;
import com.pdfoxide.creation.PageSize;

import java.nio.file.Files;
import java.nio.file.Paths;

/**
 * Example: Create PDF documents from multiple sources.
 *
 * This example demonstrates:
 * - Creating a PDF from Markdown with builder pattern
 * - Creating a PDF from HTML
 * - Creating a PDF from plain text
 * - Using PdfBuilder for customized document settings
 *
 * Usage: java CreatePdf
 */
public class CreatePdf {

    public static void main(String[] args) {
        System.out.println("PDF Creation Examples");
        System.out.println("=".repeat(60));

        try {
            // Example 1: Create from Markdown
            createFromMarkdown();

            // Example 2: Create from HTML
            createFromHtml();

            // Example 3: Create from Text
            createFromText();

            // Example 4: Create with PdfBuilder
            createWithBuilder();

            System.out.println("\n" + "=".repeat(60));
            System.out.println("✅ All PDFs created successfully!");
            System.out.println("Check current directory for: output_*.pdf");

        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Create PDF from Markdown
     */
    private static void createFromMarkdown() throws Exception {
        System.out.println("\n1. Creating from Markdown...");

        String markdown = """
                # Markdown PDF Example

                This PDF was created from **Markdown** source code.

                ## Features
                - Easy to write
                - Automatic formatting
                - Support for lists and headings

                ### Code Example
                ```
                Pdf doc = Pdf.fromMarkdown(markdown);
                doc.save("output.pdf");
                ```

                **Learn more** at [pdfoxide.github.io](https://example.com)
                """;

        Pdf doc = Pdf.fromMarkdown(markdown);
        doc.save("output_markdown.pdf");
        doc.close();

        System.out.println("   ✓ Created: output_markdown.pdf");
    }

    /**
     * Create PDF from HTML
     */
    private static void createFromHtml() throws Exception {
        System.out.println("\n2. Creating from HTML...");

        String html = """
                <html>
                <body>
                <h1>HTML PDF Example</h1>
                <p>This PDF was created from <strong>HTML</strong> source code.</p>

                <h2>Features</h2>
                <ul>
                  <li>Standard HTML markup</li>
                  <li>CSS styling support</li>
                  <li>Professional layout</li>
                </ul>

                <p><em>Created using pdf_oxide Java bindings</em></p>
                </body>
                </html>
                """;

        Pdf doc = Pdf.fromHtml(html);
        doc.save("output_html.pdf");
        doc.close();

        System.out.println("   ✓ Created: output_html.pdf");
    }

    /**
     * Create PDF from plain text
     */
    private static void createFromText() throws Exception {
        System.out.println("\n3. Creating from Text...");

        String text = """
                TEXT PDF EXAMPLE
                ================

                This PDF was created from plain text source code.

                Features:
                - Simple and straightforward
                - No markup required
                - Fast conversion

                Benefits:
                1. Easy to implement
                2. Reliable output
                3. Universal format

                Contact: example@pdfoxide.dev
                Website: https://example.com
                """;

        Pdf doc = Pdf.fromText(text);
        doc.save("output_text.pdf");
        doc.close();

        System.out.println("   ✓ Created: output_text.pdf");
    }

    /**
     * Create PDF with builder pattern and custom settings
     */
    private static void createWithBuilder() throws Exception {
        System.out.println("\n4. Creating with Builder (custom settings)...");

        String markdown = """
                # Advanced PDF Creation

                ## Document Properties

                This example demonstrates using the **PdfBuilder** to customize:
                - Document title
                - Author information
                - Keywords and subject
                - Page size and margins

                ## Benefits

                The builder pattern provides:
                - Fluent API for easy configuration
                - Type safety
                - Sensible defaults

                ## Generated By

                PDF Oxide Java Bindings v0.3.0
                """;

        Pdf doc = PdfBuilder.create()
                .title("Advanced PDF Example")
                .author("PDF Oxide Developer")
                .subject("Demonstrating PdfBuilder capabilities")
                .keywords("pdf", "builder", "example", "advanced")
                .pageSize(PageSize.A4)
                .margins(72.0, 72.0, 72.0, 72.0)  // 1 inch margins
                .fromMarkdown(markdown);

        doc.save("output_builder.pdf");
        doc.close();

        System.out.println("   ✓ Created: output_builder.pdf");
        System.out.println("   - Title: Advanced PDF Example");
        System.out.println("   - Author: PDF Oxide Developer");
        System.out.println("   - Page Size: A4");
        System.out.println("   - Margins: 1 inch");
    }
}
